print_pdf:
  name: Print PDF
  description: Prints a PDF file to the specified IPP printer.
  fields:
    entity_id:
      name: Entity
      description: The IPP printer entity to use.
      required: true
      selector:
        entity:
          integration: ipp_printer_service
    file_path:
      name: File Path
      description: The absolute path to the PDF file to print.
      required: true
      selector:
        text:
    is_local_path:
      name: Is Local Path
      description: If true, the file path is treated as a path relative to the Home Assistant local URL (e.g. /api/image_manager/1/pdf).
      required: false
      default: false
      selector:
        boolean:
    copies:
      name: Copies
      description: Number of copies to print.
      required: false
      default: 1
      selector:
        number:
          min: 1
          max: 99
          mode: box

